### ISSUE TITLE
Screenshot font

### ISSUE THREAD

**Issue by malteo** [g-e-o-m-e-t-r-i-c/tokyonight-windows-terminal#1]
Hello, thanks for the port.

What's the font featured in the screenshot? It's hecking beautiful.

(Not properly an issue, but "Discussions" is disabled for the repo. Maybe the screenshot font is missing in the README? There, that's the issue.)

**Comment by jiyometrik** [comment]
hi! the font used in these screenshots is [victor mono](https://rubjo.github.io/victor-mono/). it contains a beautiful cursive italic version!
